### PR TITLE
[CAP-2] Splitting Pipeline

### PR DESCRIPTION
**Pull request by TAsif**
# Ticket
https://flickpicker.atlassian.net/browse/CAP-2

# Description
Splitting FE Pipeline

# Type of change
- [x] New feature (non-breaking change which adds functionality)

# Tests
Manual - pipeline running

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by madhi-naga — DISMISSED** [review]

**Comment by TAsif** [comment]
run tests

**Comment by TAsif** [comment]
run tests

**Comment by TAsif** [comment]
run tests

**Comment by TAsif** [comment]
run tests

**Pull request merged**
